excluded:
- Pods
- DerivedData
opt_in_rules:
- force_unwrapping

large_tuple: 3

line_length:
    warning: 200
    error: 150

function_body_length:
    warning: 50
    error: 40

type_body_length:
    warning: 200
    error: 400

function_parameter_count:
    warning: 7
